### ISSUE TITLE
Handoff checklist

### ISSUE THREAD

**Issue by brondsem** [deafhhs/adapt#28]
- [x] deploy to heroku
- [x] reset database
- [x] load auth, audioligist, provider, settings fixtures
- [x] create new accounts with strong passwords
- [x] write down important info (url, heroku account, our contact info etc) for DHHS
